# Dependencies
gems:                [jekyll-paginate]
#markdown:            redcarpet
#highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
title:               Android Security
tagline:             'Musings about Android Security'
description:         'A website with Android security musings by <a href="https://twitter.com/marcos_placona">Marcos Placona</a>'
url:                 http://androidsecurity.info
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Marcos Placona
  url:               https://twitter.com/marcos_placona
  email:             marcos@twilio.com

# Custom vars
version:             1.0.0


# This website's repo
github:
  repo:           https://github.com/mplacona/androidsecurity.github.io

exclude:
  - templates
  - LICENSE.md
  - README.md
  - LICENSE.lanyon
  - README.lanyon

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

exclude: [vendor]